PROJECT = droneactor
PROJECT_DESCRIPTION = New project
PROJECT_VERSION = 0.1.0

DEPS = cowboy jsx uuid
dep_cowboy_commit = 2.9.0
dep_jsx = git https://github.com/talentdeficit/jsx main
dep_uuid = git https://github.com/avtobiff/erlang-uuid master

DEP_PLUGINS = cowboy

include erlang.mk
