-define(default_game_size, 4).
-define(max_game_size, 6).
-define(max_game_name_len, 20).
-define(max_player_count, 3).
-define(max_player_name_len, 20).
-define(queen_tick, 3000).
-define(drone_tick, 1000).
